//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace gcmAPI.NewPennRateService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'UsingAddressing' from namespace 'http://www.w3.org/2006/05/addressing/wsdl' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RequestRateQuoteV6SoapBinding", Namespace="http://quoting.newpenn.com")]
    public partial class RequestRateQuoteV6Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback quoteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RequestRateQuoteV6Service() {
            this.Url = global::gcmAPI.Properties.Settings.Default.gcmAPI_NewPennRateService_RequestRateQuoteV6Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event quoteCompletedEventHandler quoteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("quote", RequestNamespace="http://quoting.newpenn.com", ResponseNamespace="http://quoting.newpenn.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("quoteReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RateQuote[] quote(
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteUserId, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteWebPassword, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quotePayor, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteShipperState, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteShipperCity, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteShipperZip, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteConsigneeState, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteConsigneeCity, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteConsigneeZip, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteTerms, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteClass1, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteClass2, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteClass3, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteClass4, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteClass5, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteWeight1, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteWeight2, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteWeight3, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteWeight4, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteWeight5, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quotePurchaseOrderNumber, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteCashOnDelivery, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteAccessorial1, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteAccessorial2, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteAccessorial3, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteAccessorial4, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteAccessorial5, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteAccessorial6, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteHazard, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteFreeze, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteGuaranteedDelivery, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteOverLength, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteOverWidth, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteSkids, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string quoteDrums) {
            object[] results = this.Invoke("quote", new object[] {
                        quoteUserId,
                        quoteWebPassword,
                        quotePayor,
                        quoteShipperState,
                        quoteShipperCity,
                        quoteShipperZip,
                        quoteConsigneeState,
                        quoteConsigneeCity,
                        quoteConsigneeZip,
                        quoteTerms,
                        quoteClass1,
                        quoteClass2,
                        quoteClass3,
                        quoteClass4,
                        quoteClass5,
                        quoteWeight1,
                        quoteWeight2,
                        quoteWeight3,
                        quoteWeight4,
                        quoteWeight5,
                        quotePurchaseOrderNumber,
                        quoteCashOnDelivery,
                        quoteAccessorial1,
                        quoteAccessorial2,
                        quoteAccessorial3,
                        quoteAccessorial4,
                        quoteAccessorial5,
                        quoteAccessorial6,
                        quoteHazard,
                        quoteFreeze,
                        quoteGuaranteedDelivery,
                        quoteOverLength,
                        quoteOverWidth,
                        quoteSkids,
                        quoteDrums});
            return ((RateQuote[])(results[0]));
        }
        
        /// <remarks/>
        public void quoteAsync(
                    string quoteUserId, 
                    string quoteWebPassword, 
                    string quotePayor, 
                    string quoteShipperState, 
                    string quoteShipperCity, 
                    string quoteShipperZip, 
                    string quoteConsigneeState, 
                    string quoteConsigneeCity, 
                    string quoteConsigneeZip, 
                    string quoteTerms, 
                    string quoteClass1, 
                    string quoteClass2, 
                    string quoteClass3, 
                    string quoteClass4, 
                    string quoteClass5, 
                    string quoteWeight1, 
                    string quoteWeight2, 
                    string quoteWeight3, 
                    string quoteWeight4, 
                    string quoteWeight5, 
                    string quotePurchaseOrderNumber, 
                    string quoteCashOnDelivery, 
                    string quoteAccessorial1, 
                    string quoteAccessorial2, 
                    string quoteAccessorial3, 
                    string quoteAccessorial4, 
                    string quoteAccessorial5, 
                    string quoteAccessorial6, 
                    string quoteHazard, 
                    string quoteFreeze, 
                    string quoteGuaranteedDelivery, 
                    string quoteOverLength, 
                    string quoteOverWidth, 
                    string quoteSkids, 
                    string quoteDrums) {
            this.quoteAsync(quoteUserId, quoteWebPassword, quotePayor, quoteShipperState, quoteShipperCity, quoteShipperZip, quoteConsigneeState, quoteConsigneeCity, quoteConsigneeZip, quoteTerms, quoteClass1, quoteClass2, quoteClass3, quoteClass4, quoteClass5, quoteWeight1, quoteWeight2, quoteWeight3, quoteWeight4, quoteWeight5, quotePurchaseOrderNumber, quoteCashOnDelivery, quoteAccessorial1, quoteAccessorial2, quoteAccessorial3, quoteAccessorial4, quoteAccessorial5, quoteAccessorial6, quoteHazard, quoteFreeze, quoteGuaranteedDelivery, quoteOverLength, quoteOverWidth, quoteSkids, quoteDrums, null);
        }
        
        /// <remarks/>
        public void quoteAsync(
                    string quoteUserId, 
                    string quoteWebPassword, 
                    string quotePayor, 
                    string quoteShipperState, 
                    string quoteShipperCity, 
                    string quoteShipperZip, 
                    string quoteConsigneeState, 
                    string quoteConsigneeCity, 
                    string quoteConsigneeZip, 
                    string quoteTerms, 
                    string quoteClass1, 
                    string quoteClass2, 
                    string quoteClass3, 
                    string quoteClass4, 
                    string quoteClass5, 
                    string quoteWeight1, 
                    string quoteWeight2, 
                    string quoteWeight3, 
                    string quoteWeight4, 
                    string quoteWeight5, 
                    string quotePurchaseOrderNumber, 
                    string quoteCashOnDelivery, 
                    string quoteAccessorial1, 
                    string quoteAccessorial2, 
                    string quoteAccessorial3, 
                    string quoteAccessorial4, 
                    string quoteAccessorial5, 
                    string quoteAccessorial6, 
                    string quoteHazard, 
                    string quoteFreeze, 
                    string quoteGuaranteedDelivery, 
                    string quoteOverLength, 
                    string quoteOverWidth, 
                    string quoteSkids, 
                    string quoteDrums, 
                    object userState) {
            if ((this.quoteOperationCompleted == null)) {
                this.quoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnquoteOperationCompleted);
            }
            this.InvokeAsync("quote", new object[] {
                        quoteUserId,
                        quoteWebPassword,
                        quotePayor,
                        quoteShipperState,
                        quoteShipperCity,
                        quoteShipperZip,
                        quoteConsigneeState,
                        quoteConsigneeCity,
                        quoteConsigneeZip,
                        quoteTerms,
                        quoteClass1,
                        quoteClass2,
                        quoteClass3,
                        quoteClass4,
                        quoteClass5,
                        quoteWeight1,
                        quoteWeight2,
                        quoteWeight3,
                        quoteWeight4,
                        quoteWeight5,
                        quotePurchaseOrderNumber,
                        quoteCashOnDelivery,
                        quoteAccessorial1,
                        quoteAccessorial2,
                        quoteAccessorial3,
                        quoteAccessorial4,
                        quoteAccessorial5,
                        quoteAccessorial6,
                        quoteHazard,
                        quoteFreeze,
                        quoteGuaranteedDelivery,
                        quoteOverLength,
                        quoteOverWidth,
                        quoteSkids,
                        quoteDrums}, this.quoteOperationCompleted, userState);
        }
        
        private void OnquoteOperationCompleted(object arg) {
            if ((this.quoteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.quoteCompleted(this, new quoteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://quoting.newpenn.com")]
    public partial class RateQuote {
        
        private string quoteAccessorialDescription1Field;
        
        private string quoteAccessorialDescription2Field;
        
        private string quoteAccessorialDescription3Field;
        
        private string quoteAccessorialDescription4Field;
        
        private string quoteAccessorialDescription5Field;
        
        private string quoteAccessorialDescription6Field;
        
        private string quoteAccessorialDescriptionId1Field;
        
        private string quoteAccessorialDescriptionId2Field;
        
        private string quoteAccessorialDescriptionId3Field;
        
        private string quoteAccessorialDescriptionId4Field;
        
        private string quoteAccessorialDescriptionId5Field;
        
        private string quoteAccessorialDescriptionId6Field;
        
        private string quoteAmount1Field;
        
        private string quoteAmount2Field;
        
        private string quoteAmount3Field;
        
        private string quoteAmount4Field;
        
        private string quoteAmount5Field;
        
        private string quoteAmount6Field;
        
        private string quoteCalculatedWeightField;
        
        private string quoteCanadianDiscountDollarsField;
        
        private string quoteCanadianFrieghtChargesField;
        
        private string quoteCanadianFuelSurchargeField;
        
        private string quoteCanadianNetChargesField;
        
        private string quoteCanadianServiceChargeField;
        
        private string quoteClass1OutputField;
        
        private string quoteClass2OutputField;
        
        private string quoteClass3OutputField;
        
        private string quoteClass4OutputField;
        
        private string quoteClass5OutputField;
        
        private string quoteClass6OutputField;
        
        private string quoteClassWeightCommentField;
        
        private string quoteDiscountDollarsField;
        
        private string quoteErrorMessageField;
        
        private string quoteErrorMessageIdField;
        
        private string quoteFreightChargesField;
        
        private string quoteFuelSurchargeField;
        
        private string quoteIncentiveCanadianChargesField;
        
        private string quoteIncentiveChargesField;
        
        private string quoteMessageIdField;
        
        private string quoteMessageTextField;
        
        private string quoteNetChargesField;
        
        private string quoteNumberField;
        
        private string quoteRatePerPound1Field;
        
        private string quoteRatePerPound2Field;
        
        private string quoteRatePerPound3Field;
        
        private string quoteRatePerPound4Field;
        
        private string quoteRatePerPound5Field;
        
        private string quoteRatePerPound6Field;
        
        private string quoteServiceChargesField;
        
        private string quoteWeight1OutputField;
        
        private string quoteWeight2OutputField;
        
        private string quoteWeight3OutputField;
        
        private string quoteWeight4OutputField;
        
        private string quoteWeight5OutputField;
        
        private string quoteWeight6OutputField;
        
        private string quoteDateField;
        
        private string quoteIncentiveExpireDateField;
        
        private string quoteProjectedDeliveryDateField;
        
        private string quoteTransitDaysField;
        
        private string quoteTransitOriginPartnerCarrierCustomerServiceNumberField;
        
        private string quoteTransitOriginPartnerCarrierTerminalPhoneField;
        
        private string quoteTransitOriginPartnerCarrierTerminalTextField;
        
        private string quoteTransitDestinationPartnerCarrierTransitLinkField;
        
        private string quoteTransitOriginPartnerCarrierTransitLinkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteAccessorialDescription1 {
            get {
                return this.quoteAccessorialDescription1Field;
            }
            set {
                this.quoteAccessorialDescription1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteAccessorialDescription2 {
            get {
                return this.quoteAccessorialDescription2Field;
            }
            set {
                this.quoteAccessorialDescription2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteAccessorialDescription3 {
            get {
                return this.quoteAccessorialDescription3Field;
            }
            set {
                this.quoteAccessorialDescription3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteAccessorialDescription4 {
            get {
                return this.quoteAccessorialDescription4Field;
            }
            set {
                this.quoteAccessorialDescription4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteAccessorialDescription5 {
            get {
                return this.quoteAccessorialDescription5Field;
            }
            set {
                this.quoteAccessorialDescription5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteAccessorialDescription6 {
            get {
                return this.quoteAccessorialDescription6Field;
            }
            set {
                this.quoteAccessorialDescription6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteAccessorialDescriptionId1 {
            get {
                return this.quoteAccessorialDescriptionId1Field;
            }
            set {
                this.quoteAccessorialDescriptionId1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteAccessorialDescriptionId2 {
            get {
                return this.quoteAccessorialDescriptionId2Field;
            }
            set {
                this.quoteAccessorialDescriptionId2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteAccessorialDescriptionId3 {
            get {
                return this.quoteAccessorialDescriptionId3Field;
            }
            set {
                this.quoteAccessorialDescriptionId3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteAccessorialDescriptionId4 {
            get {
                return this.quoteAccessorialDescriptionId4Field;
            }
            set {
                this.quoteAccessorialDescriptionId4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteAccessorialDescriptionId5 {
            get {
                return this.quoteAccessorialDescriptionId5Field;
            }
            set {
                this.quoteAccessorialDescriptionId5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteAccessorialDescriptionId6 {
            get {
                return this.quoteAccessorialDescriptionId6Field;
            }
            set {
                this.quoteAccessorialDescriptionId6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteAmount1 {
            get {
                return this.quoteAmount1Field;
            }
            set {
                this.quoteAmount1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteAmount2 {
            get {
                return this.quoteAmount2Field;
            }
            set {
                this.quoteAmount2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteAmount3 {
            get {
                return this.quoteAmount3Field;
            }
            set {
                this.quoteAmount3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteAmount4 {
            get {
                return this.quoteAmount4Field;
            }
            set {
                this.quoteAmount4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteAmount5 {
            get {
                return this.quoteAmount5Field;
            }
            set {
                this.quoteAmount5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteAmount6 {
            get {
                return this.quoteAmount6Field;
            }
            set {
                this.quoteAmount6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteCalculatedWeight {
            get {
                return this.quoteCalculatedWeightField;
            }
            set {
                this.quoteCalculatedWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteCanadianDiscountDollars {
            get {
                return this.quoteCanadianDiscountDollarsField;
            }
            set {
                this.quoteCanadianDiscountDollarsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteCanadianFrieghtCharges {
            get {
                return this.quoteCanadianFrieghtChargesField;
            }
            set {
                this.quoteCanadianFrieghtChargesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteCanadianFuelSurcharge {
            get {
                return this.quoteCanadianFuelSurchargeField;
            }
            set {
                this.quoteCanadianFuelSurchargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteCanadianNetCharges {
            get {
                return this.quoteCanadianNetChargesField;
            }
            set {
                this.quoteCanadianNetChargesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteCanadianServiceCharge {
            get {
                return this.quoteCanadianServiceChargeField;
            }
            set {
                this.quoteCanadianServiceChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteClass1Output {
            get {
                return this.quoteClass1OutputField;
            }
            set {
                this.quoteClass1OutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteClass2Output {
            get {
                return this.quoteClass2OutputField;
            }
            set {
                this.quoteClass2OutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteClass3Output {
            get {
                return this.quoteClass3OutputField;
            }
            set {
                this.quoteClass3OutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteClass4Output {
            get {
                return this.quoteClass4OutputField;
            }
            set {
                this.quoteClass4OutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteClass5Output {
            get {
                return this.quoteClass5OutputField;
            }
            set {
                this.quoteClass5OutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteClass6Output {
            get {
                return this.quoteClass6OutputField;
            }
            set {
                this.quoteClass6OutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteClassWeightComment {
            get {
                return this.quoteClassWeightCommentField;
            }
            set {
                this.quoteClassWeightCommentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteDiscountDollars {
            get {
                return this.quoteDiscountDollarsField;
            }
            set {
                this.quoteDiscountDollarsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteErrorMessage {
            get {
                return this.quoteErrorMessageField;
            }
            set {
                this.quoteErrorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteErrorMessageId {
            get {
                return this.quoteErrorMessageIdField;
            }
            set {
                this.quoteErrorMessageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteFreightCharges {
            get {
                return this.quoteFreightChargesField;
            }
            set {
                this.quoteFreightChargesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteFuelSurcharge {
            get {
                return this.quoteFuelSurchargeField;
            }
            set {
                this.quoteFuelSurchargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteIncentiveCanadianCharges {
            get {
                return this.quoteIncentiveCanadianChargesField;
            }
            set {
                this.quoteIncentiveCanadianChargesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteIncentiveCharges {
            get {
                return this.quoteIncentiveChargesField;
            }
            set {
                this.quoteIncentiveChargesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteMessageId {
            get {
                return this.quoteMessageIdField;
            }
            set {
                this.quoteMessageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteMessageText {
            get {
                return this.quoteMessageTextField;
            }
            set {
                this.quoteMessageTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteNetCharges {
            get {
                return this.quoteNetChargesField;
            }
            set {
                this.quoteNetChargesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteNumber {
            get {
                return this.quoteNumberField;
            }
            set {
                this.quoteNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteRatePerPound1 {
            get {
                return this.quoteRatePerPound1Field;
            }
            set {
                this.quoteRatePerPound1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteRatePerPound2 {
            get {
                return this.quoteRatePerPound2Field;
            }
            set {
                this.quoteRatePerPound2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteRatePerPound3 {
            get {
                return this.quoteRatePerPound3Field;
            }
            set {
                this.quoteRatePerPound3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteRatePerPound4 {
            get {
                return this.quoteRatePerPound4Field;
            }
            set {
                this.quoteRatePerPound4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteRatePerPound5 {
            get {
                return this.quoteRatePerPound5Field;
            }
            set {
                this.quoteRatePerPound5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteRatePerPound6 {
            get {
                return this.quoteRatePerPound6Field;
            }
            set {
                this.quoteRatePerPound6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteServiceCharges {
            get {
                return this.quoteServiceChargesField;
            }
            set {
                this.quoteServiceChargesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteWeight1Output {
            get {
                return this.quoteWeight1OutputField;
            }
            set {
                this.quoteWeight1OutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteWeight2Output {
            get {
                return this.quoteWeight2OutputField;
            }
            set {
                this.quoteWeight2OutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteWeight3Output {
            get {
                return this.quoteWeight3OutputField;
            }
            set {
                this.quoteWeight3OutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteWeight4Output {
            get {
                return this.quoteWeight4OutputField;
            }
            set {
                this.quoteWeight4OutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteWeight5Output {
            get {
                return this.quoteWeight5OutputField;
            }
            set {
                this.quoteWeight5OutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteWeight6Output {
            get {
                return this.quoteWeight6OutputField;
            }
            set {
                this.quoteWeight6OutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteDate {
            get {
                return this.quoteDateField;
            }
            set {
                this.quoteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteIncentiveExpireDate {
            get {
                return this.quoteIncentiveExpireDateField;
            }
            set {
                this.quoteIncentiveExpireDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteProjectedDeliveryDate {
            get {
                return this.quoteProjectedDeliveryDateField;
            }
            set {
                this.quoteProjectedDeliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteTransitDays {
            get {
                return this.quoteTransitDaysField;
            }
            set {
                this.quoteTransitDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteTransitOriginPartnerCarrierCustomerServiceNumber {
            get {
                return this.quoteTransitOriginPartnerCarrierCustomerServiceNumberField;
            }
            set {
                this.quoteTransitOriginPartnerCarrierCustomerServiceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteTransitOriginPartnerCarrierTerminalPhone {
            get {
                return this.quoteTransitOriginPartnerCarrierTerminalPhoneField;
            }
            set {
                this.quoteTransitOriginPartnerCarrierTerminalPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteTransitOriginPartnerCarrierTerminalText {
            get {
                return this.quoteTransitOriginPartnerCarrierTerminalTextField;
            }
            set {
                this.quoteTransitOriginPartnerCarrierTerminalTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteTransitDestinationPartnerCarrierTransitLink {
            get {
                return this.quoteTransitDestinationPartnerCarrierTransitLinkField;
            }
            set {
                this.quoteTransitDestinationPartnerCarrierTransitLinkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string quoteTransitOriginPartnerCarrierTransitLink {
            get {
                return this.quoteTransitOriginPartnerCarrierTransitLinkField;
            }
            set {
                this.quoteTransitOriginPartnerCarrierTransitLinkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void quoteCompletedEventHandler(object sender, quoteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class quoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal quoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RateQuote[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RateQuote[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591