//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace gcmAPI.stdfRateService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RatingSoap", Namespace="http://standardforwarding.com/")]
    public partial class Rating : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetRateQuoteDetailedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRateQuoteSimpleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Rating() {
            this.Url = global::gcmAPI.Properties.Settings.Default.gcmAPI_stdfRateService_Rating;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetRateQuoteDetailedCompletedEventHandler GetRateQuoteDetailedCompleted;
        
        /// <remarks/>
        public event GetRateQuoteSimpleCompletedEventHandler GetRateQuoteSimpleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://standardforwarding.com/GetRateQuoteDetailed", RequestNamespace="http://standardforwarding.com/", ResponseNamespace="http://standardforwarding.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RateQuote GetRateQuoteDetailed(string login, string password, string originZIPCode, string destinationZIPCode, string weight, string rateClass, string terms) {
            object[] results = this.Invoke("GetRateQuoteDetailed", new object[] {
                        login,
                        password,
                        originZIPCode,
                        destinationZIPCode,
                        weight,
                        rateClass,
                        terms});
            return ((RateQuote)(results[0]));
        }
        
        /// <remarks/>
        public void GetRateQuoteDetailedAsync(string login, string password, string originZIPCode, string destinationZIPCode, string weight, string rateClass, string terms) {
            this.GetRateQuoteDetailedAsync(login, password, originZIPCode, destinationZIPCode, weight, rateClass, terms, null);
        }
        
        /// <remarks/>
        public void GetRateQuoteDetailedAsync(string login, string password, string originZIPCode, string destinationZIPCode, string weight, string rateClass, string terms, object userState) {
            if ((this.GetRateQuoteDetailedOperationCompleted == null)) {
                this.GetRateQuoteDetailedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRateQuoteDetailedOperationCompleted);
            }
            this.InvokeAsync("GetRateQuoteDetailed", new object[] {
                        login,
                        password,
                        originZIPCode,
                        destinationZIPCode,
                        weight,
                        rateClass,
                        terms}, this.GetRateQuoteDetailedOperationCompleted, userState);
        }
        
        private void OnGetRateQuoteDetailedOperationCompleted(object arg) {
            if ((this.GetRateQuoteDetailedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRateQuoteDetailedCompleted(this, new GetRateQuoteDetailedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://standardforwarding.com/GetRateQuoteSimple", RequestNamespace="http://standardforwarding.com/", ResponseNamespace="http://standardforwarding.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RateQuoteSimple GetRateQuoteSimple(string login, string password, string originZIPCode, string destinationZIPCode, string weight, string rateClass, string terms) {
            object[] results = this.Invoke("GetRateQuoteSimple", new object[] {
                        login,
                        password,
                        originZIPCode,
                        destinationZIPCode,
                        weight,
                        rateClass,
                        terms});
            return ((RateQuoteSimple)(results[0]));
        }
        
        /// <remarks/>
        public void GetRateQuoteSimpleAsync(string login, string password, string originZIPCode, string destinationZIPCode, string weight, string rateClass, string terms) {
            this.GetRateQuoteSimpleAsync(login, password, originZIPCode, destinationZIPCode, weight, rateClass, terms, null);
        }
        
        /// <remarks/>
        public void GetRateQuoteSimpleAsync(string login, string password, string originZIPCode, string destinationZIPCode, string weight, string rateClass, string terms, object userState) {
            if ((this.GetRateQuoteSimpleOperationCompleted == null)) {
                this.GetRateQuoteSimpleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRateQuoteSimpleOperationCompleted);
            }
            this.InvokeAsync("GetRateQuoteSimple", new object[] {
                        login,
                        password,
                        originZIPCode,
                        destinationZIPCode,
                        weight,
                        rateClass,
                        terms}, this.GetRateQuoteSimpleOperationCompleted, userState);
        }
        
        private void OnGetRateQuoteSimpleOperationCompleted(object arg) {
            if ((this.GetRateQuoteSimpleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRateQuoteSimpleCompleted(this, new GetRateQuoteSimpleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://standardforwarding.com/")]
    public partial class RateQuote {
        
        private string totalChargesField;
        
        private string preDiscountChargesField;
        
        private string discountAmountField;
        
        private string bydChargesField;
        
        private string bydDescriptionField;
        
        private string fSCChargesField;
        
        private string fSCDescriptionField;
        
        private string errorMessageField;
        
        private RateLineItem[] lineItemsField;
        
        /// <remarks/>
        public string TotalCharges {
            get {
                return this.totalChargesField;
            }
            set {
                this.totalChargesField = value;
            }
        }
        
        /// <remarks/>
        public string PreDiscountCharges {
            get {
                return this.preDiscountChargesField;
            }
            set {
                this.preDiscountChargesField = value;
            }
        }
        
        /// <remarks/>
        public string DiscountAmount {
            get {
                return this.discountAmountField;
            }
            set {
                this.discountAmountField = value;
            }
        }
        
        /// <remarks/>
        public string BydCharges {
            get {
                return this.bydChargesField;
            }
            set {
                this.bydChargesField = value;
            }
        }
        
        /// <remarks/>
        public string BydDescription {
            get {
                return this.bydDescriptionField;
            }
            set {
                this.bydDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string FSCCharges {
            get {
                return this.fSCChargesField;
            }
            set {
                this.fSCChargesField = value;
            }
        }
        
        /// <remarks/>
        public string FSCDescription {
            get {
                return this.fSCDescriptionField;
            }
            set {
                this.fSCDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public RateLineItem[] LineItems {
            get {
                return this.lineItemsField;
            }
            set {
                this.lineItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://standardforwarding.com/")]
    public partial class RateLineItem {
        
        private string lineNoField;
        
        private string palletsField;
        
        private string piecesField;
        
        private string weightField;
        
        private string rateClassField;
        
        private string rateField;
        
        private string chargeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string LineNo {
            get {
                return this.lineNoField;
            }
            set {
                this.lineNoField = value;
            }
        }
        
        /// <remarks/>
        public string Pallets {
            get {
                return this.palletsField;
            }
            set {
                this.palletsField = value;
            }
        }
        
        /// <remarks/>
        public string Pieces {
            get {
                return this.piecesField;
            }
            set {
                this.piecesField = value;
            }
        }
        
        /// <remarks/>
        public string Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public string RateClass {
            get {
                return this.rateClassField;
            }
            set {
                this.rateClassField = value;
            }
        }
        
        /// <remarks/>
        public string Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        public string Charge {
            get {
                return this.chargeField;
            }
            set {
                this.chargeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://standardforwarding.com/")]
    public partial class RateQuoteSimple {
        
        private string totalChargesField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public string TotalCharges {
            get {
                return this.totalChargesField;
            }
            set {
                this.totalChargesField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetRateQuoteDetailedCompletedEventHandler(object sender, GetRateQuoteDetailedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRateQuoteDetailedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRateQuoteDetailedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RateQuote Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RateQuote)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetRateQuoteSimpleCompletedEventHandler(object sender, GetRateQuoteSimpleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRateQuoteSimpleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRateQuoteSimpleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RateQuoteSimple Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RateQuoteSimple)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591