//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace gcmAPI.com.odfl.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ODRate_v1_0_SOAPBinding", Namespace="http://odfl.com/ws/ODRate-v1")]
    public partial class ODRate_v1_0 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getRateEstimateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ODRate_v1_0() {
            this.Url = global::gcmAPI.Properties.Settings.Default.gcmAPI_com_odfl_www_ODRate_v1_0;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getRateEstimateCompletedEventHandler getRateEstimateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestElementName="rateRequest", RequestNamespace="http://odfl.com/ws/ODRate-v1.0", ResponseElementName="rateResponse", ResponseNamespace="http://odfl.com/ws/ODRate-v1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("rateReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public RateResult getRateEstimate([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string originPostalCode, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string originCountry, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string destinationPostalCode, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string destinationCountry, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string requestorType, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string odfl4meUser, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string odfl4mePassword, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string odflCustomerAccount, [System.Xml.Serialization.XmlElementAttribute("freightArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] Freight[] freightArray, [System.Xml.Serialization.XmlElementAttribute("accessorialArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] Accessorial[] accessorialArray, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string mexicoServiceCenter, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string currencyFormat, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string requestReferenceNumber) {
            object[] results = this.Invoke("getRateEstimate", new object[] {
                        originPostalCode,
                        originCountry,
                        destinationPostalCode,
                        destinationCountry,
                        requestorType,
                        odfl4meUser,
                        odfl4mePassword,
                        odflCustomerAccount,
                        freightArray,
                        accessorialArray,
                        mexicoServiceCenter,
                        currencyFormat,
                        requestReferenceNumber});
            return ((RateResult)(results[0]));
        }
        
        /// <remarks/>
        public void getRateEstimateAsync(string originPostalCode, string originCountry, string destinationPostalCode, string destinationCountry, string requestorType, string odfl4meUser, string odfl4mePassword, string odflCustomerAccount, Freight[] freightArray, Accessorial[] accessorialArray, string mexicoServiceCenter, string currencyFormat, string requestReferenceNumber) {
            this.getRateEstimateAsync(originPostalCode, originCountry, destinationPostalCode, destinationCountry, requestorType, odfl4meUser, odfl4mePassword, odflCustomerAccount, freightArray, accessorialArray, mexicoServiceCenter, currencyFormat, requestReferenceNumber, null);
        }
        
        /// <remarks/>
        public void getRateEstimateAsync(string originPostalCode, string originCountry, string destinationPostalCode, string destinationCountry, string requestorType, string odfl4meUser, string odfl4mePassword, string odflCustomerAccount, Freight[] freightArray, Accessorial[] accessorialArray, string mexicoServiceCenter, string currencyFormat, string requestReferenceNumber, object userState) {
            if ((this.getRateEstimateOperationCompleted == null)) {
                this.getRateEstimateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRateEstimateOperationCompleted);
            }
            this.InvokeAsync("getRateEstimate", new object[] {
                        originPostalCode,
                        originCountry,
                        destinationPostalCode,
                        destinationCountry,
                        requestorType,
                        odfl4meUser,
                        odfl4mePassword,
                        odflCustomerAccount,
                        freightArray,
                        accessorialArray,
                        mexicoServiceCenter,
                        currencyFormat,
                        requestReferenceNumber}, this.getRateEstimateOperationCompleted, userState);
        }
        
        private void OngetRateEstimateOperationCompleted(object arg) {
            if ((this.getRateEstimateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRateEstimateCompleted(this, new getRateEstimateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://odfl.com/ws/ODRate-v1.0")]
    public partial class Freight {
        
        private string nmfcClassField;
        
        private string weightField;
        
        private string lengthField;
        
        private string widthField;
        
        private string heightField;
        
        private string handlingUnitsField;
        
        private string densityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string nmfcClass {
            get {
                return this.nmfcClassField;
            }
            set {
                this.nmfcClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string handlingUnits {
            get {
                return this.handlingUnitsField;
            }
            set {
                this.handlingUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string density {
            get {
                return this.densityField;
            }
            set {
                this.densityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://odfl.com/ws/ODRate-v1.0")]
    public partial class CityServiceDays {
        
        private string cityField;
        
        private string serviceDaysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string serviceDays {
            get {
                return this.serviceDaysField;
            }
            set {
                this.serviceDaysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://odfl.com/ws/ODRate-v1.0")]
    public partial class AccessorialCharge {
        
        private string amountField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://odfl.com/ws/ODRate-v1.0")]
    public partial class EstimateDetail {
        
        private string grossFreightChargeField;
        
        private string discountPercentageField;
        
        private string discountAmountField;
        
        private string discountedFreightChargeField;
        
        private string fuelSurchargeField;
        
        private bool variableAccessorialRateField;
        
        private string totalAccessorialChargeField;
        
        private AccessorialCharge[] accessorialChargeArrayField;
        
        private string internationalChargeField;
        
        private string netFreightChargeField;
        
        private string ratedClassField;
        
        private string guaranteedServiceOptionField;
        
        private string currencyFormatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string grossFreightCharge {
            get {
                return this.grossFreightChargeField;
            }
            set {
                this.grossFreightChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string discountPercentage {
            get {
                return this.discountPercentageField;
            }
            set {
                this.discountPercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string discountAmount {
            get {
                return this.discountAmountField;
            }
            set {
                this.discountAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string discountedFreightCharge {
            get {
                return this.discountedFreightChargeField;
            }
            set {
                this.discountedFreightChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string fuelSurcharge {
            get {
                return this.fuelSurchargeField;
            }
            set {
                this.fuelSurchargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool variableAccessorialRate {
            get {
                return this.variableAccessorialRateField;
            }
            set {
                this.variableAccessorialRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string totalAccessorialCharge {
            get {
                return this.totalAccessorialChargeField;
            }
            set {
                this.totalAccessorialChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("accessorialChargeArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public AccessorialCharge[] accessorialChargeArray {
            get {
                return this.accessorialChargeArrayField;
            }
            set {
                this.accessorialChargeArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string internationalCharge {
            get {
                return this.internationalChargeField;
            }
            set {
                this.internationalChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string netFreightCharge {
            get {
                return this.netFreightChargeField;
            }
            set {
                this.netFreightChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ratedClass {
            get {
                return this.ratedClassField;
            }
            set {
                this.ratedClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string guaranteedServiceOption {
            get {
                return this.guaranteedServiceOptionField;
            }
            set {
                this.guaranteedServiceOptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string currencyFormat {
            get {
                return this.currencyFormatField;
            }
            set {
                this.currencyFormatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://odfl.com/ws/ODRate-v1.0")]
    public partial class ServiceCenter {
        
        private string alphaCodeField;
        
        private string addressField;
        
        private string cityStateZipField;
        
        private string countryField;
        
        private string emailAddressField;
        
        private string faxField;
        
        private string managerField;
        
        private string nameField;
        
        private string phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string alphaCode {
            get {
                return this.alphaCodeField;
            }
            set {
                this.alphaCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string cityStateZip {
            get {
                return this.cityStateZipField;
            }
            set {
                this.cityStateZipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string manager {
            get {
                return this.managerField;
            }
            set {
                this.managerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://odfl.com/ws/ODRate-v1.0")]
    public partial class RateResult {
        
        private ServiceCenter originatingServiceCenterField;
        
        private ServiceCenter destinationServiceCenterField;
        
        private string originatingInterlineCarrierNameField;
        
        private string originatingInterlineScacField;
        
        private string destinationInterlineCarrierNameField;
        
        private string destinationInterlineScacField;
        
        private EstimateDetail rateEstimateField;
        
        private string referenceNumberField;
        
        private CityServiceDays[] destinationCitiesArrayField;
        
        private string[] errorMessagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ServiceCenter originatingServiceCenter {
            get {
                return this.originatingServiceCenterField;
            }
            set {
                this.originatingServiceCenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ServiceCenter destinationServiceCenter {
            get {
                return this.destinationServiceCenterField;
            }
            set {
                this.destinationServiceCenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string originatingInterlineCarrierName {
            get {
                return this.originatingInterlineCarrierNameField;
            }
            set {
                this.originatingInterlineCarrierNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string originatingInterlineScac {
            get {
                return this.originatingInterlineScacField;
            }
            set {
                this.originatingInterlineScacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string destinationInterlineCarrierName {
            get {
                return this.destinationInterlineCarrierNameField;
            }
            set {
                this.destinationInterlineCarrierNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string destinationInterlineScac {
            get {
                return this.destinationInterlineScacField;
            }
            set {
                this.destinationInterlineScacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public EstimateDetail rateEstimate {
            get {
                return this.rateEstimateField;
            }
            set {
                this.rateEstimateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("destinationCitiesArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public CityServiceDays[] destinationCitiesArray {
            get {
                return this.destinationCitiesArrayField;
            }
            set {
                this.destinationCitiesArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errorMessages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] errorMessages {
            get {
                return this.errorMessagesField;
            }
            set {
                this.errorMessagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://odfl.com/ws/ODRate-v1.0")]
    public partial class Accessorial {
        
        private string codeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void getRateEstimateCompletedEventHandler(object sender, getRateEstimateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRateEstimateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRateEstimateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RateResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RateResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591