//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace gcmAPI.AAACooperRateService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsGenRateEstimateSOAP", Namespace="http://tempuri.org/wsGenRateEstimate/")]
    public partial class wsGenRateEstimate : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallwsGenRateEstimateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsGenRateEstimate() {
            this.Url = global::gcmAPI.Properties.Settings.Default.gcmAPI_AAACooperRateService_wsGenRateEstimate;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallwsGenRateEstimateCompletedEventHandler CallwsGenRateEstimateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsGenRateEstimate/NewOperation", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RateEstimateResponseVO", Namespace="http://tempuri.org/wsGenRateEstimate/")]
        public RateEstimateResponseVO CallwsGenRateEstimate([System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/wsGenRateEstimate/")] RateEstimateRequestVO RateEstimateRequestVO) {
            object[] results = this.Invoke("CallwsGenRateEstimate", new object[] {
                        RateEstimateRequestVO});
            return ((RateEstimateResponseVO)(results[0]));
        }
        
        /// <remarks/>
        public void CallwsGenRateEstimateAsync(RateEstimateRequestVO RateEstimateRequestVO) {
            this.CallwsGenRateEstimateAsync(RateEstimateRequestVO, null);
        }
        
        /// <remarks/>
        public void CallwsGenRateEstimateAsync(RateEstimateRequestVO RateEstimateRequestVO, object userState) {
            if ((this.CallwsGenRateEstimateOperationCompleted == null)) {
                this.CallwsGenRateEstimateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallwsGenRateEstimateOperationCompleted);
            }
            this.InvokeAsync("CallwsGenRateEstimate", new object[] {
                        RateEstimateRequestVO}, this.CallwsGenRateEstimateOperationCompleted, userState);
        }
        
        private void OnCallwsGenRateEstimateOperationCompleted(object arg) {
            if ((this.CallwsGenRateEstimateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallwsGenRateEstimateCompleted(this, new CallwsGenRateEstimateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/wsGenRateEstimate/")]
    public partial class RateEstimateRequestVO {
        
        private string tokenField;
        
        private string customerNumberField;
        
        private string originCityField;
        
        private string originStateField;
        
        private string originZipField;
        
        private string originCountryCodeField;
        
        private string destinationCityField;
        
        private string destinationStateField;
        
        private string destinationZipField;
        
        private string destinCountryCodeField;
        
        private string whoAmIField;
        
        private string billDateField;
        
        private string cODAmountField;
        
        private string cODPayTypeField;
        
        private string cODFeePaidByField;
        
        private string fullCoverageField;
        
        private string fullCoverageAmountField;
        
        private string prePaidCollectField;
        
        private string totalPalletCountField;
        
        private RateEstimateRequestVOAccLine[] accLineField;
        
        private RateEstimateRequestVORateEstimateRequestLine[] rateEstimateRequestLineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OriginCity {
            get {
                return this.originCityField;
            }
            set {
                this.originCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OriginState {
            get {
                return this.originStateField;
            }
            set {
                this.originStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OriginZip {
            get {
                return this.originZipField;
            }
            set {
                this.originZipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OriginCountryCode {
            get {
                return this.originCountryCodeField;
            }
            set {
                this.originCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DestinationCity {
            get {
                return this.destinationCityField;
            }
            set {
                this.destinationCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DestinationState {
            get {
                return this.destinationStateField;
            }
            set {
                this.destinationStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DestinationZip {
            get {
                return this.destinationZipField;
            }
            set {
                this.destinationZipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DestinCountryCode {
            get {
                return this.destinCountryCodeField;
            }
            set {
                this.destinCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WhoAmI {
            get {
                return this.whoAmIField;
            }
            set {
                this.whoAmIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillDate {
            get {
                return this.billDateField;
            }
            set {
                this.billDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CODAmount {
            get {
                return this.cODAmountField;
            }
            set {
                this.cODAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CODPayType {
            get {
                return this.cODPayTypeField;
            }
            set {
                this.cODPayTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CODFeePaidBy {
            get {
                return this.cODFeePaidByField;
            }
            set {
                this.cODFeePaidByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FullCoverage {
            get {
                return this.fullCoverageField;
            }
            set {
                this.fullCoverageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FullCoverageAmount {
            get {
                return this.fullCoverageAmountField;
            }
            set {
                this.fullCoverageAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PrePaidCollect {
            get {
                return this.prePaidCollectField;
            }
            set {
                this.prePaidCollectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotalPalletCount {
            get {
                return this.totalPalletCountField;
            }
            set {
                this.totalPalletCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AccLine", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RateEstimateRequestVOAccLine[] AccLine {
            get {
                return this.accLineField;
            }
            set {
                this.accLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RateEstimateRequestLine", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RateEstimateRequestVORateEstimateRequestLine[] RateEstimateRequestLine {
            get {
                return this.rateEstimateRequestLineField;
            }
            set {
                this.rateEstimateRequestLineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/wsGenRateEstimate/")]
    public partial class RateEstimateRequestVOAccLine {
        
        private string accCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AccCode {
            get {
                return this.accCodeField;
            }
            set {
                this.accCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/wsGenRateEstimate/")]
    public partial class RateEstimateRequestVORateEstimateRequestLine {
        
        private string weightField;
        
        private string classField;
        
        private string handlingUnitsField;
        
        private string handlingUnitTypeField;
        
        private string hazmatField;
        
        private string cubeUField;
        
        private string lengthField;
        
        private string heightField;
        
        private string widthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HandlingUnits {
            get {
                return this.handlingUnitsField;
            }
            set {
                this.handlingUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HandlingUnitType {
            get {
                return this.handlingUnitTypeField;
            }
            set {
                this.handlingUnitTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Hazmat {
            get {
                return this.hazmatField;
            }
            set {
                this.hazmatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CubeU {
            get {
                return this.cubeUField;
            }
            set {
                this.cubeUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/wsGenRateEstimate/")]
    public partial class RateEstimateResponseVO {
        
        private string errorMessageField;
        
        private string estimateNumberField;
        
        private string estimateSequenceField;
        
        private string shipperNumberField;
        
        private string shipperNameField;
        
        private string originCityField;
        
        private string originStateField;
        
        private string originZipField;
        
        private string originCountryCodeField;
        
        private string originTerminalField;
        
        private string originTerminalPhoneField;
        
        private string consigneeNumberField;
        
        private string consigneeNameField;
        
        private string destinationCityField;
        
        private string destinationStateField;
        
        private string destinationZipField;
        
        private string destinCountryCodeField;
        
        private string destinTerminalField;
        
        private string destinTerminalPhoneField;
        
        private string billDateField;
        
        private string prePaidCollectField;
        
        private string minimumChargeField;
        
        private string tariffField;
        
        private string discountField;
        
        private string rateBaseField;
        
        private string houseHoldGoodsRateBaseField;
        
        private string totalActualWeightField;
        
        private string totalAsWeightField;
        
        private string detailLineCountField;
        
        private string densityField;
        
        private string fuelSurchargePercentField;
        
        private string interlineFlagField;
        
        private string totalChargesField;
        
        private string totalMiscField;
        
        private string informationCodeField;
        
        private string informationMessageField;
        
        private string cODAmountField;
        
        private string fullCoverageAmountField;
        
        private string cODPayTypeField;
        
        private string cODFeeField;
        
        private string unitOfMeasureField;
        
        private string whoAmIField;
        
        private string fullValueCoverageField;
        
        private string totalTransitField;
        
        private string totalPalletCountField;
        
        private RateEstimateResponseVORateEstimateResponseLine[] rateEstimateResponseLineField;
        
        private string guaranteedDeliveryFeeField;
        
        private string totChgWGuarDelFeeField;
        
        private string totChgWFVCFeeField;
        
        private string totChgWFVCAndGDAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EstimateNumber {
            get {
                return this.estimateNumberField;
            }
            set {
                this.estimateNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EstimateSequence {
            get {
                return this.estimateSequenceField;
            }
            set {
                this.estimateSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipperNumber {
            get {
                return this.shipperNumberField;
            }
            set {
                this.shipperNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipperName {
            get {
                return this.shipperNameField;
            }
            set {
                this.shipperNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OriginCity {
            get {
                return this.originCityField;
            }
            set {
                this.originCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OriginState {
            get {
                return this.originStateField;
            }
            set {
                this.originStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OriginZip {
            get {
                return this.originZipField;
            }
            set {
                this.originZipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OriginCountryCode {
            get {
                return this.originCountryCodeField;
            }
            set {
                this.originCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OriginTerminal {
            get {
                return this.originTerminalField;
            }
            set {
                this.originTerminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OriginTerminalPhone {
            get {
                return this.originTerminalPhoneField;
            }
            set {
                this.originTerminalPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ConsigneeNumber {
            get {
                return this.consigneeNumberField;
            }
            set {
                this.consigneeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ConsigneeName {
            get {
                return this.consigneeNameField;
            }
            set {
                this.consigneeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DestinationCity {
            get {
                return this.destinationCityField;
            }
            set {
                this.destinationCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DestinationState {
            get {
                return this.destinationStateField;
            }
            set {
                this.destinationStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DestinationZip {
            get {
                return this.destinationZipField;
            }
            set {
                this.destinationZipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DestinCountryCode {
            get {
                return this.destinCountryCodeField;
            }
            set {
                this.destinCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DestinTerminal {
            get {
                return this.destinTerminalField;
            }
            set {
                this.destinTerminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DestinTerminalPhone {
            get {
                return this.destinTerminalPhoneField;
            }
            set {
                this.destinTerminalPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillDate {
            get {
                return this.billDateField;
            }
            set {
                this.billDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PrePaidCollect {
            get {
                return this.prePaidCollectField;
            }
            set {
                this.prePaidCollectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MinimumCharge {
            get {
                return this.minimumChargeField;
            }
            set {
                this.minimumChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Tariff {
            get {
                return this.tariffField;
            }
            set {
                this.tariffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Discount {
            get {
                return this.discountField;
            }
            set {
                this.discountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RateBase {
            get {
                return this.rateBaseField;
            }
            set {
                this.rateBaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HouseHoldGoodsRateBase {
            get {
                return this.houseHoldGoodsRateBaseField;
            }
            set {
                this.houseHoldGoodsRateBaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotalActualWeight {
            get {
                return this.totalActualWeightField;
            }
            set {
                this.totalActualWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotalAsWeight {
            get {
                return this.totalAsWeightField;
            }
            set {
                this.totalAsWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DetailLineCount {
            get {
                return this.detailLineCountField;
            }
            set {
                this.detailLineCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Density {
            get {
                return this.densityField;
            }
            set {
                this.densityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FuelSurchargePercent {
            get {
                return this.fuelSurchargePercentField;
            }
            set {
                this.fuelSurchargePercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InterlineFlag {
            get {
                return this.interlineFlagField;
            }
            set {
                this.interlineFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotalCharges {
            get {
                return this.totalChargesField;
            }
            set {
                this.totalChargesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotalMisc {
            get {
                return this.totalMiscField;
            }
            set {
                this.totalMiscField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InformationCode {
            get {
                return this.informationCodeField;
            }
            set {
                this.informationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InformationMessage {
            get {
                return this.informationMessageField;
            }
            set {
                this.informationMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CODAmount {
            get {
                return this.cODAmountField;
            }
            set {
                this.cODAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FullCoverageAmount {
            get {
                return this.fullCoverageAmountField;
            }
            set {
                this.fullCoverageAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CODPayType {
            get {
                return this.cODPayTypeField;
            }
            set {
                this.cODPayTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CODFee {
            get {
                return this.cODFeeField;
            }
            set {
                this.cODFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UnitOfMeasure {
            get {
                return this.unitOfMeasureField;
            }
            set {
                this.unitOfMeasureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WhoAmI {
            get {
                return this.whoAmIField;
            }
            set {
                this.whoAmIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FullValueCoverage {
            get {
                return this.fullValueCoverageField;
            }
            set {
                this.fullValueCoverageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotalTransit {
            get {
                return this.totalTransitField;
            }
            set {
                this.totalTransitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotalPalletCount {
            get {
                return this.totalPalletCountField;
            }
            set {
                this.totalPalletCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RateEstimateResponseLine", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RateEstimateResponseVORateEstimateResponseLine[] RateEstimateResponseLine {
            get {
                return this.rateEstimateResponseLineField;
            }
            set {
                this.rateEstimateResponseLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GuaranteedDeliveryFee {
            get {
                return this.guaranteedDeliveryFeeField;
            }
            set {
                this.guaranteedDeliveryFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotChgWGuarDelFee {
            get {
                return this.totChgWGuarDelFeeField;
            }
            set {
                this.totChgWGuarDelFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotChgWFVCFee {
            get {
                return this.totChgWFVCFeeField;
            }
            set {
                this.totChgWFVCFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotChgWFVCAndGDA {
            get {
                return this.totChgWFVCAndGDAField;
            }
            set {
                this.totChgWFVCAndGDAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/wsGenRateEstimate/")]
    public partial class RateEstimateResponseVORateEstimateResponseLine {
        
        private string handlingUnitsField;
        
        private string handlingUnitTypeField;
        
        private string hazMatField;
        
        private string descriptionField;
        
        private string classField;
        
        private string weightField;
        
        private string rateField;
        
        private string chargesField;
        
        private string miscField;
        
        private string accessorialField;
        
        private string prePaidCollectField;
        
        private string lengthField;
        
        private string widthField;
        
        private string heightField;
        
        private string cubeUnitField;
        
        private string cubeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HandlingUnits {
            get {
                return this.handlingUnitsField;
            }
            set {
                this.handlingUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HandlingUnitType {
            get {
                return this.handlingUnitTypeField;
            }
            set {
                this.handlingUnitTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HazMat {
            get {
                return this.hazMatField;
            }
            set {
                this.hazMatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Charges {
            get {
                return this.chargesField;
            }
            set {
                this.chargesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Misc {
            get {
                return this.miscField;
            }
            set {
                this.miscField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Accessorial {
            get {
                return this.accessorialField;
            }
            set {
                this.accessorialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PrePaidCollect {
            get {
                return this.prePaidCollectField;
            }
            set {
                this.prePaidCollectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CubeUnit {
            get {
                return this.cubeUnitField;
            }
            set {
                this.cubeUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cube {
            get {
                return this.cubeField;
            }
            set {
                this.cubeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void CallwsGenRateEstimateCompletedEventHandler(object sender, CallwsGenRateEstimateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallwsGenRateEstimateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallwsGenRateEstimateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RateEstimateResponseVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RateEstimateResponseVO)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591