//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcmAPI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wstest.globalcargomanager.com/RateService2.asmx")]
        public string gcmAPI_wstest_RateService2 {
            get {
                return ((string)(this["gcmAPI_wstest_RateService2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wsportal.aaacooper.com:8188/wsportal20/wsGenEst")]
        public string gcmAPI_AAACooperRateService_wsGenRateEstimate {
            get {
                return ((string)(this["gcmAPI_AAACooperRateService_wsGenRateEstimate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.globalcargomanager.com/RateService2.asmx")]
        public string gcmAPI_gcmWebService_RateService2 {
            get {
                return ((string)(this["gcmAPI_gcmWebService_RateService2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://onlinetools.ups.com/webservices/Pickup")]
        public string gcmAPI_UPS_PackagePickupService_PickupService {
            get {
                return ((string)(this["gcmAPI_UPS_PackagePickupService_PickupService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.standardforwarding.com/STDFServices/Rating.asmx")]
        public string gcmAPI_stdfRateService_Rating {
            get {
                return ((string)(this["gcmAPI_stdfRateService_Rating"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.rrts.com/rating/ratequote.asmx")]
        public string gcmAPI_RRTS_WebService_RateQuote {
            get {
                return ((string)(this["gcmAPI_RRTS_WebService_RateQuote"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://legacy.daytonfreight.com/WebServices_v1.0/ShippingService.asmx")]
        public string gcmAPI_com_daytonfreight_www_ShippingService {
            get {
                return ((string)(this["gcmAPI_com_daytonfreight_www_ShippingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.odfl.com:443/wsRate_v1/services/ODRate")]
        public string gcmAPI_com_odfl_www_ODRate_v1_0 {
            get {
                return ((string)(this["gcmAPI_com_odfl_www_ODRate_v1_0"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.rlcarriers.com/1.0.2/RateQuoteService.asmx")]
        public string gcmAPI_RL_CarriersAPI_RateQuoteService {
            get {
                return ((string)(this["gcmAPI_RL_CarriersAPI_RateQuoteService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.rlcarriers.com/1.0.2/TransitTimesService.asmx")]
        public string gcmAPI_RL_CarriersTransitTimes_API_TransitTimesService {
            get {
                return ((string)(this["gcmAPI_RL_CarriersTransitTimes_API_TransitTimesService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.estes-express.com/tools/rating/ratequote/v3.0/services/RateQuoteServi" +
            "ce")]
        public string gcmAPI_Estes_RateWebServ_RateQuoteService {
            get {
                return ((string)(this["gcmAPI_Estes_RateWebServ_RateQuoteService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://tgif1.bestovernite.com:10010/web/services/TQUOTEAPI.TQUOTEAPIHttpSoap11End" +
            "point/")]
        public string gcmAPI_Best_Overnite_RateService_TQUOTEAPI {
            get {
                return ((string)(this["gcmAPI_Best_Overnite_RateService_TQUOTEAPI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9080/rateQuoteWSV6/services/RequestRateQuoteV6")]
        public string gcmAPI_NewPennRateService_RequestRateQuoteV6Service {
            get {
                return ((string)(this["gcmAPI_NewPennRateService_RequestRateQuoteV6Service"]));
            }
        }
    }
}
