//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace gcmAPI.RL_CarriersAPI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RateQuoteServiceSoap", Namespace="http://www.rlcarriers.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseReply))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseRequest))]
    public partial class RateQuoteService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetRateQuoteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPalletTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPalletTypeByPointsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RateQuoteService() {
            this.Url = global::gcmAPI.Properties.Settings.Default.gcmAPI_RL_CarriersAPI_RateQuoteService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetRateQuoteCompletedEventHandler GetRateQuoteCompleted;
        
        /// <remarks/>
        public event GetPalletTypesCompletedEventHandler GetPalletTypesCompleted;
        
        /// <remarks/>
        public event GetPalletTypeByPointsCompletedEventHandler GetPalletTypeByPointsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.rlcarriers.com/GetRateQuote", RequestNamespace="http://www.rlcarriers.com/", ResponseNamespace="http://www.rlcarriers.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RateQuoteReply GetRateQuote(string APIKey, RateQuoteRequest request) {
            object[] results = this.Invoke("GetRateQuote", new object[] {
                        APIKey,
                        request});
            return ((RateQuoteReply)(results[0]));
        }
        
        /// <remarks/>
        public void GetRateQuoteAsync(string APIKey, RateQuoteRequest request) {
            this.GetRateQuoteAsync(APIKey, request, null);
        }
        
        /// <remarks/>
        public void GetRateQuoteAsync(string APIKey, RateQuoteRequest request, object userState) {
            if ((this.GetRateQuoteOperationCompleted == null)) {
                this.GetRateQuoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRateQuoteOperationCompleted);
            }
            this.InvokeAsync("GetRateQuote", new object[] {
                        APIKey,
                        request}, this.GetRateQuoteOperationCompleted, userState);
        }
        
        private void OnGetRateQuoteOperationCompleted(object arg) {
            if ((this.GetRateQuoteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRateQuoteCompleted(this, new GetRateQuoteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.rlcarriers.com/GetPalletTypes", RequestNamespace="http://www.rlcarriers.com/", ResponseNamespace="http://www.rlcarriers.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RateQuotePalletReply GetPalletTypes(string APIKey) {
            object[] results = this.Invoke("GetPalletTypes", new object[] {
                        APIKey});
            return ((RateQuotePalletReply)(results[0]));
        }
        
        /// <remarks/>
        public void GetPalletTypesAsync(string APIKey) {
            this.GetPalletTypesAsync(APIKey, null);
        }
        
        /// <remarks/>
        public void GetPalletTypesAsync(string APIKey, object userState) {
            if ((this.GetPalletTypesOperationCompleted == null)) {
                this.GetPalletTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPalletTypesOperationCompleted);
            }
            this.InvokeAsync("GetPalletTypes", new object[] {
                        APIKey}, this.GetPalletTypesOperationCompleted, userState);
        }
        
        private void OnGetPalletTypesOperationCompleted(object arg) {
            if ((this.GetPalletTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPalletTypesCompleted(this, new GetPalletTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.rlcarriers.com/GetPalletTypeByPoints", RequestNamespace="http://www.rlcarriers.com/", ResponseNamespace="http://www.rlcarriers.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RateQuotePalletReply GetPalletTypeByPoints(string APIKey, string MyRLCID, string originCity, string originZip, string destinationCity, string destinationZip) {
            object[] results = this.Invoke("GetPalletTypeByPoints", new object[] {
                        APIKey,
                        MyRLCID,
                        originCity,
                        originZip,
                        destinationCity,
                        destinationZip});
            return ((RateQuotePalletReply)(results[0]));
        }
        
        /// <remarks/>
        public void GetPalletTypeByPointsAsync(string APIKey, string MyRLCID, string originCity, string originZip, string destinationCity, string destinationZip) {
            this.GetPalletTypeByPointsAsync(APIKey, MyRLCID, originCity, originZip, destinationCity, destinationZip, null);
        }
        
        /// <remarks/>
        public void GetPalletTypeByPointsAsync(string APIKey, string MyRLCID, string originCity, string originZip, string destinationCity, string destinationZip, object userState) {
            if ((this.GetPalletTypeByPointsOperationCompleted == null)) {
                this.GetPalletTypeByPointsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPalletTypeByPointsOperationCompleted);
            }
            this.InvokeAsync("GetPalletTypeByPoints", new object[] {
                        APIKey,
                        MyRLCID,
                        originCity,
                        originZip,
                        destinationCity,
                        destinationZip}, this.GetPalletTypeByPointsOperationCompleted, userState);
        }
        
        private void OnGetPalletTypeByPointsOperationCompleted(object arg) {
            if ((this.GetPalletTypeByPointsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPalletTypeByPointsCompleted(this, new GetPalletTypeByPointsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rlcarriers.com/")]
    public partial class RateQuoteRequest : BaseRequest {
        
        private QuoteType quoteTypeField;
        
        private decimal cODAmountField;
        
        private ServicePoint originField;
        
        private ServicePoint destinationField;
        
        private Item[] itemsField;
        
        private decimal declaredValueField;
        
        private Accessorial[] accessorialsField;
        
        private int overDimensionPcsField;
        
        private Pallet[] palletsField;
        
        /// <remarks/>
        public QuoteType QuoteType {
            get {
                return this.quoteTypeField;
            }
            set {
                this.quoteTypeField = value;
            }
        }
        
        /// <remarks/>
        public decimal CODAmount {
            get {
                return this.cODAmountField;
            }
            set {
                this.cODAmountField = value;
            }
        }
        
        /// <remarks/>
        public ServicePoint Origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public ServicePoint Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public Item[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public decimal DeclaredValue {
            get {
                return this.declaredValueField;
            }
            set {
                this.declaredValueField = value;
            }
        }
        
        /// <remarks/>
        public Accessorial[] Accessorials {
            get {
                return this.accessorialsField;
            }
            set {
                this.accessorialsField = value;
            }
        }
        
        /// <remarks/>
        public int OverDimensionPcs {
            get {
                return this.overDimensionPcsField;
            }
            set {
                this.overDimensionPcsField = value;
            }
        }
        
        /// <remarks/>
        public Pallet[] Pallets {
            get {
                return this.palletsField;
            }
            set {
                this.palletsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rlcarriers.com/")]
    public enum QuoteType {
        
        /// <remarks/>
        AlaskaHawaii,
        
        /// <remarks/>
        Domestic,
        
        /// <remarks/>
        International,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rlcarriers.com/")]
    public partial class ServicePoint {
        
        private string cityField;
        
        private string stateOrProvinceField;
        
        private string zipOrPostalCodeField;
        
        private string countryCodeField;
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string StateOrProvince {
            get {
                return this.stateOrProvinceField;
            }
            set {
                this.stateOrProvinceField = value;
            }
        }
        
        /// <remarks/>
        public string ZipOrPostalCode {
            get {
                return this.zipOrPostalCodeField;
            }
            set {
                this.zipOrPostalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rlcarriers.com/")]
    public partial class PalletType {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rlcarriers.com/")]
    public partial class HourlyWindow {
        
        private string startField;
        
        private string endField;
        
        /// <remarks/>
        public string Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        public string End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rlcarriers.com/")]
    public partial class ServiceLevel {
        
        private string titleField;
        
        private string codeField;
        
        private string quoteNumberField;
        
        private int serviceDaysField;
        
        private string chargeField;
        
        private string netChargeField;
        
        private HourlyWindow hourlyWindowField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string QuoteNumber {
            get {
                return this.quoteNumberField;
            }
            set {
                this.quoteNumberField = value;
            }
        }
        
        /// <remarks/>
        public int ServiceDays {
            get {
                return this.serviceDaysField;
            }
            set {
                this.serviceDaysField = value;
            }
        }
        
        /// <remarks/>
        public string Charge {
            get {
                return this.chargeField;
            }
            set {
                this.chargeField = value;
            }
        }
        
        /// <remarks/>
        public string NetCharge {
            get {
                return this.netChargeField;
            }
            set {
                this.netChargeField = value;
            }
        }
        
        /// <remarks/>
        public HourlyWindow HourlyWindow {
            get {
                return this.hourlyWindowField;
            }
            set {
                this.hourlyWindowField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rlcarriers.com/")]
    public partial class Message {
        
        private string titleField;
        
        private string textField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rlcarriers.com/")]
    public partial class Charge {
        
        private string typeField;
        
        private string titleField;
        
        private string weightField;
        
        private string rateField;
        
        private string amountField;
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public string Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rlcarriers.com/")]
    public partial class ServiceCenter {
        
        private string codeField;
        
        private string locationField;
        
        private string zipCodeField;
        
        private string phoneField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rlcarriers.com/")]
    public partial class QuoteDetails {
        
        private ServicePoint originField;
        
        private ServicePoint destinationField;
        
        private ServiceCenter originServiceCenterField;
        
        private ServiceCenter destinationServiceCenterField;
        
        private string customerDiscountsField;
        
        private Charge[] chargesField;
        
        private Message[] messagesField;
        
        private ServiceLevel[] serviceLevelsField;
        
        /// <remarks/>
        public ServicePoint Origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public ServicePoint Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public ServiceCenter OriginServiceCenter {
            get {
                return this.originServiceCenterField;
            }
            set {
                this.originServiceCenterField = value;
            }
        }
        
        /// <remarks/>
        public ServiceCenter DestinationServiceCenter {
            get {
                return this.destinationServiceCenterField;
            }
            set {
                this.destinationServiceCenterField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerDiscounts {
            get {
                return this.customerDiscountsField;
            }
            set {
                this.customerDiscountsField = value;
            }
        }
        
        /// <remarks/>
        public Charge[] Charges {
            get {
                return this.chargesField;
            }
            set {
                this.chargesField = value;
            }
        }
        
        /// <remarks/>
        public Message[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        public ServiceLevel[] ServiceLevels {
            get {
                return this.serviceLevelsField;
            }
            set {
                this.serviceLevelsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RateQuotePalletReply))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RateQuoteReply))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rlcarriers.com/")]
    public partial class BaseReply {
        
        private string customerDataField;
        
        private bool wasSuccessField;
        
        private string[] messagesField;
        
        /// <remarks/>
        public string CustomerData {
            get {
                return this.customerDataField;
            }
            set {
                this.customerDataField = value;
            }
        }
        
        /// <remarks/>
        public bool WasSuccess {
            get {
                return this.wasSuccessField;
            }
            set {
                this.wasSuccessField = value;
            }
        }
        
        /// <remarks/>
        public string[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rlcarriers.com/")]
    public partial class RateQuotePalletReply : BaseReply {
        
        private PalletType[] resultField;
        
        /// <remarks/>
        public PalletType[] Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rlcarriers.com/")]
    public partial class RateQuoteReply : BaseReply {
        
        private QuoteDetails resultField;
        
        /// <remarks/>
        public QuoteDetails Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rlcarriers.com/")]
    public partial class Pallet {
        
        private string codeField;
        
        private int weightField;
        
        private int quantityField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public int Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rlcarriers.com/")]
    public partial class Item {
        
        private string classField;
        
        private float weightField;
        
        private float widthField;
        
        private float heightField;
        
        private float lengthField;
        
        /// <remarks/>
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        public float Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public float Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public float Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public float Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RateQuoteRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rlcarriers.com/")]
    public partial class BaseRequest {
        
        private string customerDataField;
        
        /// <remarks/>
        public string CustomerData {
            get {
                return this.customerDataField;
            }
            set {
                this.customerDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rlcarriers.com/")]
    public enum Accessorial {
        
        /// <remarks/>
        InsideDelivery,
        
        /// <remarks/>
        ResidentialPickup,
        
        /// <remarks/>
        ResidentialDelivery,
        
        /// <remarks/>
        OriginLiftgate,
        
        /// <remarks/>
        DestinationLiftgate,
        
        /// <remarks/>
        DeliveryNotification,
        
        /// <remarks/>
        Freezable,
        
        /// <remarks/>
        Hazmat,
        
        /// <remarks/>
        InsidePickup,
        
        /// <remarks/>
        LimitedAccessPickup,
        
        /// <remarks/>
        DockPickup,
        
        /// <remarks/>
        DockDelivery,
        
        /// <remarks/>
        AirportPickup,
        
        /// <remarks/>
        AirportDelivery,
        
        /// <remarks/>
        LimitedAccessDelivery,
        
        /// <remarks/>
        CubicFeet,
        
        /// <remarks/>
        KeepFromFreezing,
        
        /// <remarks/>
        DoorToDoor,
        
        /// <remarks/>
        COD,
        
        /// <remarks/>
        SortAndSegregate,
        
        /// <remarks/>
        OverDimension,
        
        /// <remarks/>
        ZeroFuelSurcharge,
        
        /// <remarks/>
        Tradeshow,
        
        /// <remarks/>
        DishMachineInsideDelivery,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetRateQuoteCompletedEventHandler(object sender, GetRateQuoteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRateQuoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRateQuoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RateQuoteReply Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RateQuoteReply)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetPalletTypesCompletedEventHandler(object sender, GetPalletTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPalletTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPalletTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RateQuotePalletReply Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RateQuotePalletReply)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetPalletTypeByPointsCompletedEventHandler(object sender, GetPalletTypeByPointsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPalletTypeByPointsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPalletTypeByPointsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RateQuotePalletReply Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RateQuotePalletReply)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591