//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace gcmAPI.Estes_RateWebServ {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="rateBinding", Namespace="http://ws.estesexpress.com/ratequote")]
    public partial class RateQuoteService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback echoOperationCompleted;
        
        private AuthenticationType authField;
        
        private System.Threading.SendOrPostCallback getQuoteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RateQuoteService() {
            this.Url = global::gcmAPI.Properties.Settings.Default.gcmAPI_Estes_RateWebServ_RateQuoteService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthenticationType auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event echoCompletedEventHandler echoCompleted;
        
        /// <remarks/>
        public event getQuoteCompletedEventHandler getQuoteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.estesexpress.com/ratequote/echo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("echoResponse", Namespace="http://ws.estesexpress.com/ratequote")]
        public string echo([System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.estesexpress.com/ratequote")] EchoRequestType echoRequest) {
            object[] results = this.Invoke("echo", new object[] {
                        echoRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void echoAsync(EchoRequestType echoRequest) {
            this.echoAsync(echoRequest, null);
        }
        
        /// <remarks/>
        public void echoAsync(EchoRequestType echoRequest, object userState) {
            if ((this.echoOperationCompleted == null)) {
                this.echoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnechoOperationCompleted);
            }
            this.InvokeAsync("echo", new object[] {
                        echoRequest}, this.echoOperationCompleted, userState);
        }
        
        private void OnechoOperationCompleted(object arg) {
            if ((this.echoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.echoCompleted(this, new echoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("auth")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.estesexpress.com/ratequote/getQuote", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("rateQuote", Namespace="http://ws.estesexpress.com/schema/2017/07/ratequote")]
        public rateQuote getQuote([System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.estesexpress.com/schema/2017/07/ratequote")] rateRequest rateRequest) {
            object[] results = this.Invoke("getQuote", new object[] {
                        rateRequest});
            return ((rateQuote)(results[0]));
        }
        
        /// <remarks/>
        public void getQuoteAsync(rateRequest rateRequest) {
            this.getQuoteAsync(rateRequest, null);
        }
        
        /// <remarks/>
        public void getQuoteAsync(rateRequest rateRequest, object userState) {
            if ((this.getQuoteOperationCompleted == null)) {
                this.getQuoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetQuoteOperationCompleted);
            }
            this.InvokeAsync("getQuote", new object[] {
                        rateRequest}, this.getQuoteOperationCompleted, userState);
        }
        
        private void OngetQuoteOperationCompleted(object arg) {
            if ((this.getQuoteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getQuoteCompleted(this, new getQuoteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.estesexpress.com/ratequote")]
    [System.Xml.Serialization.XmlRootAttribute("auth", Namespace="http://ws.estesexpress.com/ratequote", IsNullable=false)]
    public partial class AuthenticationType : System.Web.Services.Protocols.SoapHeader {
        
        private string userField;
        
        private string passwordField;
        
        /// <remarks/>
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.estesexpress.com/schema/2017/07/ratequote")]
    public partial class AccessorialInfoType {
        
        private string codeField;
        
        private string descriptionField;
        
        private decimal chargeField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal charge {
            get {
                return this.chargeField;
            }
            set {
                this.chargeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.estesexpress.com/schema/2017/07/ratequote")]
    public partial class PricingInfoType {
        
        private System.DateTime deliveryDateField;
        
        private System.DateTime deliveryTimeField;
        
        private string serviceLevelField;
        
        private decimal minChargeField;
        
        private bool minChargeFieldSpecified;
        
        private decimal discountField;
        
        private bool discountFieldSpecified;
        
        private decimal totalDiscountField;
        
        private bool totalDiscountFieldSpecified;
        
        private decimal standardPriceField;
        
        private bool standardPriceFieldSpecified;
        
        private decimal guaranteedPriceField;
        
        private bool guaranteedPriceFieldSpecified;
        
        private AccessorialInfoType[] accessorialInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime deliveryDate {
            get {
                return this.deliveryDateField;
            }
            set {
                this.deliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime deliveryTime {
            get {
                return this.deliveryTimeField;
            }
            set {
                this.deliveryTimeField = value;
            }
        }
        
        /// <remarks/>
        public string serviceLevel {
            get {
                return this.serviceLevelField;
            }
            set {
                this.serviceLevelField = value;
            }
        }
        
        /// <remarks/>
        public decimal minCharge {
            get {
                return this.minChargeField;
            }
            set {
                this.minChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minChargeSpecified {
            get {
                return this.minChargeFieldSpecified;
            }
            set {
                this.minChargeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal discount {
            get {
                return this.discountField;
            }
            set {
                this.discountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool discountSpecified {
            get {
                return this.discountFieldSpecified;
            }
            set {
                this.discountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal totalDiscount {
            get {
                return this.totalDiscountField;
            }
            set {
                this.totalDiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalDiscountSpecified {
            get {
                return this.totalDiscountFieldSpecified;
            }
            set {
                this.totalDiscountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal standardPrice {
            get {
                return this.standardPriceField;
            }
            set {
                this.standardPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool standardPriceSpecified {
            get {
                return this.standardPriceFieldSpecified;
            }
            set {
                this.standardPriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal guaranteedPrice {
            get {
                return this.guaranteedPriceField;
            }
            set {
                this.guaranteedPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool guaranteedPriceSpecified {
            get {
                return this.guaranteedPriceFieldSpecified;
            }
            set {
                this.guaranteedPriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("accessorial", IsNullable=false)]
        public AccessorialInfoType[] accessorialInfo {
            get {
                return this.accessorialInfoField;
            }
            set {
                this.accessorialInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.estesexpress.com/schema/2017/07/ratequote")]
    public partial class CommodityInfoType {
        
        private decimal classField;
        
        private string piecesField;
        
        private PackagingType pieceTypeField;
        
        private bool pieceTypeFieldSpecified;
        
        private string weightField;
        
        private DimensionsType dimensionsField;
        
        private decimal rateField;
        
        private decimal chargeField;
        
        /// <remarks/>
        public decimal @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string pieces {
            get {
                return this.piecesField;
            }
            set {
                this.piecesField = value;
            }
        }
        
        /// <remarks/>
        public PackagingType pieceType {
            get {
                return this.pieceTypeField;
            }
            set {
                this.pieceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pieceTypeSpecified {
            get {
                return this.pieceTypeFieldSpecified;
            }
            set {
                this.pieceTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public DimensionsType dimensions {
            get {
                return this.dimensionsField;
            }
            set {
                this.dimensionsField = value;
            }
        }
        
        /// <remarks/>
        public decimal rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        public decimal charge {
            get {
                return this.chargeField;
            }
            set {
                this.chargeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.estesexpress.com/schema/vocabulary")]
    public enum PackagingType {
        
        /// <remarks/>
        BD,
        
        /// <remarks/>
        BG,
        
        /// <remarks/>
        BK,
        
        /// <remarks/>
        BL,
        
        /// <remarks/>
        BR,
        
        /// <remarks/>
        BX,
        
        /// <remarks/>
        CN,
        
        /// <remarks/>
        CR,
        
        /// <remarks/>
        CS,
        
        /// <remarks/>
        CT,
        
        /// <remarks/>
        CY,
        
        /// <remarks/>
        DR,
        
        /// <remarks/>
        JC,
        
        /// <remarks/>
        KT,
        
        /// <remarks/>
        PC,
        
        /// <remarks/>
        PK,
        
        /// <remarks/>
        PL,
        
        /// <remarks/>
        PT,
        
        /// <remarks/>
        RE,
        
        /// <remarks/>
        RL,
        
        /// <remarks/>
        SK,
        
        /// <remarks/>
        TL,
        
        /// <remarks/>
        TO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.estesexpress.com/schema/2017/07/ratequote")]
    public partial class DimensionsType {
        
        private string lengthField;
        
        private string widthField;
        
        private string heightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.estesexpress.com/schema/2017/07/ratequote")]
    public partial class RateQuoteType {
        
        private string quoteNumberField;
        
        private string accountField;
        
        private PointType originPointField;
        
        private PointType destinationPointField;
        
        private string payorField;
        
        private string shipmentTermsField;
        
        private PickupType pickupField;
        
        private string liabilityField;
        
        private decimal declaredValueField;
        
        private bool declaredValueFieldSpecified;
        
        private YesNoBlankType hazmatField;
        
        private bool hazmatFieldSpecified;
        
        private YesNoBlankType stackableField;
        
        private bool stackableFieldSpecified;
        
        private string foodWarehouseField;
        
        private string equipmentTypeField;
        
        private YesNoBlankType declaredValueWaivedField;
        
        private bool declaredValueWaivedFieldSpecified;
        
        private string laneField;
        
        private string[] disclaimerField;
        
        private CommodityInfoType[] commodityInfoField;
        
        private PricingInfoType[] pricingField;
        
        private string[] infoField;
        
        /// <remarks/>
        public string quoteNumber {
            get {
                return this.quoteNumberField;
            }
            set {
                this.quoteNumberField = value;
            }
        }
        
        /// <remarks/>
        public string account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        public PointType originPoint {
            get {
                return this.originPointField;
            }
            set {
                this.originPointField = value;
            }
        }
        
        /// <remarks/>
        public PointType destinationPoint {
            get {
                return this.destinationPointField;
            }
            set {
                this.destinationPointField = value;
            }
        }
        
        /// <remarks/>
        public string payor {
            get {
                return this.payorField;
            }
            set {
                this.payorField = value;
            }
        }
        
        /// <remarks/>
        public string shipmentTerms {
            get {
                return this.shipmentTermsField;
            }
            set {
                this.shipmentTermsField = value;
            }
        }
        
        /// <remarks/>
        public PickupType pickup {
            get {
                return this.pickupField;
            }
            set {
                this.pickupField = value;
            }
        }
        
        /// <remarks/>
        public string liability {
            get {
                return this.liabilityField;
            }
            set {
                this.liabilityField = value;
            }
        }
        
        /// <remarks/>
        public decimal declaredValue {
            get {
                return this.declaredValueField;
            }
            set {
                this.declaredValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool declaredValueSpecified {
            get {
                return this.declaredValueFieldSpecified;
            }
            set {
                this.declaredValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public YesNoBlankType hazmat {
            get {
                return this.hazmatField;
            }
            set {
                this.hazmatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hazmatSpecified {
            get {
                return this.hazmatFieldSpecified;
            }
            set {
                this.hazmatFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public YesNoBlankType stackable {
            get {
                return this.stackableField;
            }
            set {
                this.stackableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stackableSpecified {
            get {
                return this.stackableFieldSpecified;
            }
            set {
                this.stackableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string foodWarehouse {
            get {
                return this.foodWarehouseField;
            }
            set {
                this.foodWarehouseField = value;
            }
        }
        
        /// <remarks/>
        public string equipmentType {
            get {
                return this.equipmentTypeField;
            }
            set {
                this.equipmentTypeField = value;
            }
        }
        
        /// <remarks/>
        public YesNoBlankType declaredValueWaived {
            get {
                return this.declaredValueWaivedField;
            }
            set {
                this.declaredValueWaivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool declaredValueWaivedSpecified {
            get {
                return this.declaredValueWaivedFieldSpecified;
            }
            set {
                this.declaredValueWaivedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string lane {
            get {
                return this.laneField;
            }
            set {
                this.laneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("text", IsNullable=false)]
        public string[] disclaimer {
            get {
                return this.disclaimerField;
            }
            set {
                this.disclaimerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("commodity", IsNullable=false)]
        public CommodityInfoType[] commodityInfo {
            get {
                return this.commodityInfoField;
            }
            set {
                this.commodityInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("price", IsNullable=false)]
        public PricingInfoType[] pricing {
            get {
                return this.pricingField;
            }
            set {
                this.pricingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("message", IsNullable=false)]
        public string[] info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.estesexpress.com/schema/2017/07/ratequote")]
    public partial class PointType {
        
        private string countryCodeField;
        
        private string postalCodeField;
        
        private string cityField;
        
        private string stateProvinceField;
        
        /// <remarks/>
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string stateProvince {
            get {
                return this.stateProvinceField;
            }
            set {
                this.stateProvinceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.estesexpress.com/schema/2017/07/ratequote")]
    public partial class PickupType {
        
        private System.DateTime dateField;
        
        private System.DateTime readyField;
        
        private bool readyFieldSpecified;
        
        private System.DateTime closeField;
        
        private bool closeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime ready {
            get {
                return this.readyField;
            }
            set {
                this.readyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool readySpecified {
            get {
                return this.readyFieldSpecified;
            }
            set {
                this.readyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime close {
            get {
                return this.closeField;
            }
            set {
                this.closeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool closeSpecified {
            get {
                return this.closeFieldSpecified;
            }
            set {
                this.closeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.estesexpress.com/schema/2017/07/ratequote")]
    public enum YesNoBlankType {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.estesexpress.com/schema/2017/07/ratequote")]
    public partial class FullCommoditiesType {
        
        private FullCommodityType[] commodityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("commodity")]
        public FullCommodityType[] commodity {
            get {
                return this.commodityField;
            }
            set {
                this.commodityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.estesexpress.com/schema/2017/07/ratequote")]
    public partial class FullCommodityType {
        
        private BaseCommodityType baseCommodityField;
        
        private string piecesField;
        
        private PackagingType pieceTypeField;
        
        private DimensionsType dimensionsField;
        
        /// <remarks/>
        public BaseCommodityType baseCommodity {
            get {
                return this.baseCommodityField;
            }
            set {
                this.baseCommodityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string pieces {
            get {
                return this.piecesField;
            }
            set {
                this.piecesField = value;
            }
        }
        
        /// <remarks/>
        public PackagingType pieceType {
            get {
                return this.pieceTypeField;
            }
            set {
                this.pieceTypeField = value;
            }
        }
        
        /// <remarks/>
        public DimensionsType dimensions {
            get {
                return this.dimensionsField;
            }
            set {
                this.dimensionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.estesexpress.com/schema/2017/07/ratequote")]
    public partial class BaseCommodityType {
        
        private decimal classField;
        
        private string weightField;
        
        /// <remarks/>
        public decimal @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.estesexpress.com/schema/2017/07/ratequote")]
    public partial class BaseCommoditiesType {
        
        private BaseCommodityType[] commodityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("commodity")]
        public BaseCommodityType[] commodity {
            get {
                return this.commodityField;
            }
            set {
                this.commodityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.estesexpress.com/ratequote")]
    public partial class EchoRequestType {
        
        private string inputField;
        
        /// <remarks/>
        public string input {
            get {
                return this.inputField;
            }
            set {
                this.inputField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.estesexpress.com/schema/2017/07/ratequote")]
    public partial class rateRequest {
        
        private string requestIDField;
        
        private string accountField;
        
        private PointType originPointField;
        
        private PointType destinationPointField;
        
        private string payorField;
        
        private string termsField;
        
        private PickupType pickupField;
        
        private string liabilityField;
        
        private decimal declaredValueField;
        
        private bool declaredValueFieldSpecified;
        
        private YesNoBlankType hazmatField;
        
        private bool hazmatFieldSpecified;
        
        private YesNoBlankType stackableField;
        
        private bool stackableFieldSpecified;
        
        private string foodWarehouseField;
        
        private string equipmentTypeField;
        
        private YesNoBlankType declaredValueWaivedField;
        
        private bool declaredValueWaivedFieldSpecified;
        
        private string sortSegregatePiecesField;
        
        private object itemField;
        
        private string[] accessorialsField;
        
        /// <remarks/>
        public string requestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        public string account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        public PointType originPoint {
            get {
                return this.originPointField;
            }
            set {
                this.originPointField = value;
            }
        }
        
        /// <remarks/>
        public PointType destinationPoint {
            get {
                return this.destinationPointField;
            }
            set {
                this.destinationPointField = value;
            }
        }
        
        /// <remarks/>
        public string payor {
            get {
                return this.payorField;
            }
            set {
                this.payorField = value;
            }
        }
        
        /// <remarks/>
        public string terms {
            get {
                return this.termsField;
            }
            set {
                this.termsField = value;
            }
        }
        
        /// <remarks/>
        public PickupType pickup {
            get {
                return this.pickupField;
            }
            set {
                this.pickupField = value;
            }
        }
        
        /// <remarks/>
        public string liability {
            get {
                return this.liabilityField;
            }
            set {
                this.liabilityField = value;
            }
        }
        
        /// <remarks/>
        public decimal declaredValue {
            get {
                return this.declaredValueField;
            }
            set {
                this.declaredValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool declaredValueSpecified {
            get {
                return this.declaredValueFieldSpecified;
            }
            set {
                this.declaredValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public YesNoBlankType hazmat {
            get {
                return this.hazmatField;
            }
            set {
                this.hazmatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hazmatSpecified {
            get {
                return this.hazmatFieldSpecified;
            }
            set {
                this.hazmatFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public YesNoBlankType stackable {
            get {
                return this.stackableField;
            }
            set {
                this.stackableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stackableSpecified {
            get {
                return this.stackableFieldSpecified;
            }
            set {
                this.stackableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string foodWarehouse {
            get {
                return this.foodWarehouseField;
            }
            set {
                this.foodWarehouseField = value;
            }
        }
        
        /// <remarks/>
        public string equipmentType {
            get {
                return this.equipmentTypeField;
            }
            set {
                this.equipmentTypeField = value;
            }
        }
        
        /// <remarks/>
        public YesNoBlankType declaredValueWaived {
            get {
                return this.declaredValueWaivedField;
            }
            set {
                this.declaredValueWaivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool declaredValueWaivedSpecified {
            get {
                return this.declaredValueWaivedFieldSpecified;
            }
            set {
                this.declaredValueWaivedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string sortSegregatePieces {
            get {
                return this.sortSegregatePiecesField;
            }
            set {
                this.sortSegregatePiecesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("baseCommodities", typeof(BaseCommoditiesType))]
        [System.Xml.Serialization.XmlElementAttribute("fullCommodities", typeof(FullCommoditiesType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("accessorialCode", IsNullable=false)]
        public string[] accessorials {
            get {
                return this.accessorialsField;
            }
            set {
                this.accessorialsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.estesexpress.com/schema/2017/07/ratequote")]
    public partial class rateQuote {
        
        private string requestIDField;
        
        private RateQuoteType quoteField;
        
        /// <remarks/>
        public string requestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        public RateQuoteType quote {
            get {
                return this.quoteField;
            }
            set {
                this.quoteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void echoCompletedEventHandler(object sender, echoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class echoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal echoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void getQuoteCompletedEventHandler(object sender, getQuoteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getQuoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getQuoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public rateQuote Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((rateQuote)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591